### PR TITLE
Added ebuilds for Pale Moon 29.1.0

### PR DESCRIPTION
**Pull request by CaseOf**
Hi deu,
This PR is for the new PM update, 29.1.0.
I’ve readded GCC 9.3 in supported compilers since the issue is now fixed as Tobin told me as quoted in #106.

### CODE REVIEW

**Comment by jeandestouches** [comment]
ping

**Comment by CaseOf** [comment]
@jeandestouches if you want to use my fork until deu merges this PR, you can do `cd /var/db/repos/palemoon; git remote set-url origin https://github.com/CaseOf/palemoon-overlay.git` and then do backward when deu merges it.

**Comment by jeandestouches** [comment]
@CaseOf Very handy, I'll do that. Thanks

**Comment by deu** [comment]
Sorry for the huge delay. :\

**Pull request merged**
